name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 61

    steps:
      # 1. 拉取仓库代码
      - uses: actions/checkout@v4

      # 2. 设置环境变量
      - name: Set environment variables
        run: |
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> $GITHUB_ENV

      # 3. 生成 wrangler.toml，包含 account_id
      - name: Create wrangler.toml
        run: |
          sed -e "s/\$USERNAME/$USERNAME/g" \
              -e "s/\$PASSWORD/$PASSWORD/g" \
              -e "s/\$BUCKET_NAME/$BUCKET_NAME/g" \
              wrangler.toml.template > wrangler.toml
          
          # 确保 account_id 被写入
          echo "account_id = \"$CLOUDFLARE_ACCOUNT_ID\"" >> wrangler.toml
          
          cat wrangler.toml

      # 4. 安装最新 Wrangler CLI（v4）
      - name: Install Wrangler CLI
        run: npm install -g wrangler@latest

      # 5. 验证 token 是否有效
      - name: Verify Cloudflare token
        run: npx wrangler whoami

      # 6. 构建 & 部署 Worker
      - name: Build & Deploy Worker
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
